name: packer
description: "Flutter packer project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  excel: ^4.0.6
  provider: ^6.1.1
  pdf: ^3.10.7
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/icon/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700